### ISSUE TITLE
Daily Quest completed despite not being present in the GUI

### ISSUE THREAD

**Issue by Zaoldieck** [Iridium-Development/IridiumSkyblock#652] opened 2022-04-17 01:56 UTC
I found this bug wich allow you to complete daily quests that arent on the dailymission's GUI

I tryed to reproduce the bug, and for the purpose of test, I tried the whole thing on a new and clean server. and I left the iridium skyblock plugin with its original default settings without changing any settings.

I tried to perform the actions required by a daily quest that was not present among the four randomly drawn for today.
the mission should not have been able to complete but it has completed

/version
[03:53:51 INFO]: --------------------------------------------------
[03:53:51 INFO]: Versione di CMI: 9.1.3.3 SqLite-> 9.1.4.1
[03:53:51 INFO]: CMILib: 1.1.2.5
[03:53:51 INFO]: Server: Paper(411) 1.17.1-R0.1-SNAPSHOT
[03:53:51 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[03:53:51 INFO]: Modules -> 55 enabled 1 disabled: votifier
[03:53:51 INFO]: --------------------------------------------------
/is about
[03:54:09 INFO]: Plugin Name: IridiumSkyblock
[03:54:09 INFO]: Plugin Version: 3.2.8
[03:54:09 INFO]: Plugin Author: Peaches_MLG
[03:54:09 INFO]: Plugin Contributors: das_, SlashRemix, DoctaEnkoda
[03:54:09 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG

**Screenshots**
i recorded a video where i replicate the problem
[https://streamable.com/5d0zqb](https://streamable.com/5d0zqb)

**Logs**
no errors in console.

**Comment by dlsf** [comment] 2022-04-20 20:37
Duplicate of #605. Please use the older issue if you want to add information which could help us.

**Closed by dlsf** 2022-04-20 20:37 UTC
Labels: bug, unconfirmed
