### ISSUE TITLE
Often some daily missions do not give rewards in /is rewards

### ISSUE THREAD

**Issue by Overzing** [Iridium-Development/IridiumSkyblock#846] opened 2024-05-12 15:21 UTC
**Describe the bug**

**To Reproduce**
Complete a some daily missions
go to /is rewards and many don't appear

**Server and Plugin Version**
This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Plugin version: 4.0.9.1

https://api.mclo.gs/1/raw/MlABdmj

**Comment by PeachesMLG** [comment] 2024-05-12 15:51
```
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: java.sql.SQLException: Unable to run insert stmt on object com.iridium.iridiumteams.database.TeamMission@7dcc5f91: INSERT INTO `team_mission` (`mission_name` ,`mission_level` ,`expiration` ,`team_id` ) VALUES (?,?,?,?)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:396)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:53)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.managers.IslandManager.getTeamMission(IslandManager.java:576)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.managers.IslandManager.getTeamMission(IslandManager.java:50)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumteams.gui.MissionGUI.getItem(MissionGUI.java:73)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumteams.gui.MissionGUI.addContent(MissionGUI.java:67)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumteams.gui.MissionGUI.getInventory(MissionGUI.java:45)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumteams.managers.MissionManager.generateMissionData(MissionManager.java:171)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumteams.listeners.PlayerJoinListener.lambda$onPlayerJoin$1(PlayerJoinListener.java:36)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: team_mission.mission_name, team_mission.mission_level, team_mission.team_id)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1179)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1190)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.core.DB.execute(DB.java:985)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:1054)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:122)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:121)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:185)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	at IridiumSkyblock-4.0.9.1.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[10:51:56] [Craft Scheduler Thread - 76 - IridiumSkyblock/WARN]: 	... 17 more
```

**Comment by oo7bgame** [comment] 2024-05-21 15:24
news?

**Comment by sh0inx** [comment] 2024-05-21 15:26
none yet, we'll update the issue when we fix it

**Comment by sh0inx** [comment] 2024-11-20 15:58
Duplicate of #809

**Closed by sh0inx** 2024-11-20 15:58 UTC
Labels: bug, unconfirmed
