### ISSUE TITLE
Shop and Upgrades keep reseting at every restart

### ISSUE THREAD

**Issue by SkmVD** [Iridium-Development/IridiumSkyblock#114] opened 2021-06-02 22:30 UTC
> [00:27:43] [Server thread/ERROR]: [IridiumSkyblock] Failed to parse plugins/IridiumSkyblock/upgrades.yml: Cannot construct instance of `com.iridium.iridiumcore.utils.Placeholder` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: (File); line: 31, column: 9] (through reference chain: com.iridium.iridiumskyblock.configs.Upgrades["sizeUpgrade"]->com.iridium.iridiumskyblock.Upgrade["upgrades"]->java.util.LinkedHashMap["1"]->com.iridium.iridiumskyblock.upgrades.SizeUpgrade["placeholders"]->java.util.Collections$SingletonList[1])
> [00:27:43] [Server thread/ERROR]: [IridiumSkyblock] Failed to parse plugins/IridiumSkyblock/shop.yml: Unrecognized field "purchasable" (class com.iridium.iridiumskyblock.shop.ShopItem), not marked as ignorable (8 known properties: "sellReward", "buyCost", "lore", "defaultAmount", "type", "name", "slot", "command"])
at [Source: (File); line: 77, column: 22] (through reference chain: com.iridium.iridiumskyblock.configs.Shop["items"]->java.util.LinkedHashMap["Blocks"]->java.util.ArrayList[0]->com.iridium.iridiumskyblock.shop.ShopItem["purchasable"])

**Comment by dlsf** [comment] 2021-06-02 22:31
Duplicate of #112

**Closed by dlsf** 2021-06-02 22:31 UTC
Labels: bug, duplicate
