### ISSUE TITLE
Daily's not in the GUI are obtainable

### ISSUE THREAD

**Issue by Wilbert-Garcia** [Iridium-Development/IridiumSkyblock#650] opened 2022-04-13 02:46 UTC
**Describe the bug**
Players can complete daily's not showing up in gui, /is missions -> Daily's

**To Reproduce**
1. Install just Iridium Skyblock and Vault on a fresh server
2. Do /is missions -> daily's and do a daily that doesn't show up in the gui (you can look at missions.yml to find out the daily's not in the gui to see how to complete them)
3. Once you finish the Daily that isnt in the gui you'll obtain the reward

**Expected behavior**
Daily's that show up in the gui should be the only ones that are Obtainable.

**Server and Plugin Version**
`/version` 
This server is running Paper version git-Paper-215 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7f65b0b)
`/is about`
Plugin Name: IridiumSkyblock
Plugin Version: 3.2.8
Plugin Author: Peaches_MLG
Plugin Contributors: das_, SlashRemix, DoctaEnkoda
Plugin Donations: www.patreon.com/Peaches_MLG

**Screenshots**

![2022-04-12_22-21](https://user-images.githubusercontent.com/56326080/163088049-b5613428-ec4c-48dc-a953-7defd4e88acd.png)
![2022-04-12_22-21_1](https://user-images.githubusercontent.com/56326080/163088071-cb280d43-e62b-4e06-9132-3ea3872ef2e9.png)

**Logs**
I was told by TheWoofest just to have vault and Iridium that's why I have the economy error.
https://mclo.gs/jln07xr

**Additional context**
I noticed that daily's rotated about 4 times within a span of about 7 mins from when I joined the world I attached a screenshot of that happening, could it be that they are all loading in that's why players can get daily's that don't show up in the gui? The last screenshot is what it stayed at before I did the Miner daily that wasn't in the gui at that point.
![2022-04-12_22-07](https://user-images.githubusercontent.com/56326080/163088398-60f8932e-ab15-4b5a-80ca-21757c971d8f.png)
![2022-04-12_22-13](https://user-images.githubusercontent.com/56326080/163088411-6cd4a844-c6db-4756-8d5f-a3822c9bcee5.png)
![2022-04-12_22-14](https://user-images.githubusercontent.com/56326080/163088418-ddd7fd54-3d22-40f5-885e-c02fb18a5689.png)
![2022-04-12_22-14_1](https://user-images.githubusercontent.com/56326080/163088434-f31ccddb-46bc-4213-b3f7-9ea1e35f89b5.png)

**Comment by dlsf** [comment] 2022-04-20 20:39
Duplicate of #605. Please add new info which might help us in the older issue.

**Closed by dlsf** 2022-04-20 20:39 UTC
Labels: bug, unconfirmed
