### ISSUE TITLE
Console database error2 (pls don't close if u don't see right)

### ISSUE THREAD

**Issue by ChibeMeliodas** [Iridium-Development/IridiumSkyblock#777] opened 2023-12-18 20:14 UTC
They closed my issue, without solving it and without seeing what was written, it is a similar error, but they are different problems, since it is version 4.0.8 and the paper version is 1.20.2

[17:10:46 WARN]: java.sql.SQLException: Unable to run insert stmt on object com.iridium.iridiumteams.database.TeamMissionData@284d5891: INSERT INTO `team_mission_data` (`mission_id` ,`mission_index` ,`progress` ) VALUES (?,?,?)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:396)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:38)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:212)
[17:10:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[17:10:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:10:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:10:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:10:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:10:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:10:46 WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: team_mission_data.mission_id, team_mission_data.mission_index)
[17:10:46 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[17:10:46 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[17:10:46 WARN]:        at org.sqlite.core.DB.execute(DB.java:985)
[17:10:46 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:1054)
[17:10:46 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:122)
[17:10:46 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
[17:10:46 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:121)
[17:10:46 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:185)
[17:10:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[17:10:46 WARN]:        ... 11 more

**Comment by PeachesMLG** [comment] 2023-12-18 21:04
Just to clarify this is a duplicate of https://github.com/Iridium-Development/IridiumSkyblock/issues/725 Like stated in the original issue report

The versions specified don't make a difference here. Its something we will be working on fixing eventually, but there is no eta for it yet

**Closed by PeachesMLG** 2023-12-18 21:04 UTC
Labels: bug, unconfirmed
