### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mcde777** [Iridium-Development/IridiumSkyblock#113] opened 2021-06-02 22:30 UTC
Hello,
if I want to create an island with "/ is" there is an error in the console.

Server Version: 1.12.2 (Paper)
Plugin Version: 3.0.1
Console Log: https://pastebin.com/khiX6qzC

**Comment by dlsf** [comment] 2021-06-02 22:33
Duplicate of #89

**Closed by dlsf** 2021-06-02 22:33 UTC
Labels: bug, duplicate
