### ISSUE TITLE
Error when Creating an island

### ISSUE THREAD

**Issue by kampf4keksGER** [Iridium-Development/IridiumSkyblock#106] opened 2021-06-01 19:16 UTC
https://pastebin.com/MTTv7XE0

**Comment by kampf4keksGER** [comment] 2021-06-01 19:21
(i changed nothing in the Files)

**Comment by PeachesMLG** [comment] 2021-06-01 21:03
Duplicate of https://github.com/Iridium-Development/IridiumSkyblock/issues/89

**Closed by PeachesMLG** 2021-06-01 21:03 UTC
