### ISSUE TITLE
Island Value changes Randomly

### ISSUE THREAD

**Issue by CayeOficial** [Iridium-Development/IridiumSkyblock#324] opened 2021-07-28 20:48 UTC
Hi, I have a problem, the user island level is going down and up randomly.

One player had 600k island value and 100k suddenly disappeared

Now, a user had 112 island value, and an error came up on the console and it went down to 12.
https://pastebin.ubuntu.com/p/yMk83Fdfzn/

Then, that same user, went up to 212 without placing any blocks or anything, and then it went back down to 12. I have been on his island and doing manual calculations, he has 1 spawner and 4 iron blocks (100 + 4x3 = 112), so the is value is so bugged.
https://pastebin.ubuntu.com/p/N4g4J7pcxg/

Edit:
Version: 3.0.7 (spigot)
Server 1.8.8

**Comment by xReveres** [comment] 2021-07-28 21:12
I think this problem is similar to this: #305

**Comment by MertUnverdi** [comment] 2021-08-01 11:07
Duplicate of #305

**Closed by MertUnverdi** 2021-08-01 11:07 UTC
Labels: bug, duplicate, not confirmed
