### ISSUE TITLE
MySQL error spam in console and sync error

### ISSUE THREAD

**Issue by itsmemac** [Iridium-Development/IridiumSkyblock#184] opened 2021-06-18 15:23 UTC
**Server version :** git-Paper-772 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Plugin version :** 3.0.4

**Plugins in the server :** 
`AngelChest, AnimatedScoreboard, AuctionMaster, AureliumSkills, BloodInMinecraft, ChatInjector, ChestSort, Citizens, CommandMineRewards, CommandRegions, CommandWhitelist, DeluxeMenus, DiscordSRV, EnderContainers, Essentials, EssentialsChat, EternalNature, ExtremeLevelMobs, FastCraft, FloatingPets, FriendsRELOADED, GSit, GoldenCrates, HolographicDisplays, IPWhitelist, IridiumSkyblock, JetsMinions, LiteBans, LuckPerms, MAmbience, Maintenance, MineableSpawners, Minepacks, MiniMOTD, Multiverse-Core, MysqlEcoBridge, MysqlEconomyBank, NametagEdit, NexEngine, NoRain, OSZOAntiWDL, OnDeath, PlaceItemsOnGroundRebuilt, PlaceholderAPI, PlayerKits, ProtocolLib, RessourcesRespawn, RotatingHeads, Sentinel, ServerTutorialPlus, ServerUtils, SetSpawn, TAB, TAB-BukkitBridge, TitleManager, TreasureChest, UltraCustomizer, Vault, VoidGenerator, WDLCompanion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, eZProtector and spark`

**Error logs :**  (No startup errors found - only happens when user actions)
https://paste.lucko.me/aIohn207D1
https://paste.lucko.me/eDchuOU6Nk
https://paste.lucko.me/j6OzuFehNm

**How to reproduce the issues ? :** 
1. Enable MySQL in sql.yml
2. Start server

**When it happens ?**
When player upgrades the generator, completes mission, gains crystal this error happens
After upgrading level 3 upgrade of ore gen, sometimes the generator resets back to level 1 (reloading the plugin using plugin manager or restart of server syncs it back to level 3 upgrade)

**Alternative which works** 
Switching to flat file works without issues

**Comment by dlsf** [comment] 2021-06-18 17:15
Duplicate of #164 and #166

**Closed by dlsf** 2021-06-18 17:15 UTC
