### ISSUE TITLE
Game breaking bug (Infinite rewards)

### ISSUE THREAD

**Issue by treasurebro123** [Iridium-Development/IridiumSkyblock#923] opened 2024-11-19 19:35 UTC
### Steps to Reproduce

1. Complete multiple missions but don't claim the reward until you have done so.
2. In /is rewards use mouse to left click to claim rewards infinitely. 

### Expected Behavior

I expect for the reward to be claimed and the icon to go away. 

### Actual Behavior

You are able to claim the reward over and over again and get unlimited money.

### Server Software & Minecraft Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72) You are running the latest version

### IridiumSkyblock version

4.1.0 Beta 3

### Additional Comments

I noticed that a fully upgraded island size seems to overlap another island next to it if it is fully upgraded size as well. I also found that visitors to an island are able to kill mobs with a bow even with mob killing permission turned off. There is also a bug that when you withdraw crystals from is bank you are not able to deposit them back. Running the is deposit command prompts an error message and "right click to redeem" does nothing.

**Comment by treasurebro123** [comment] 2024-11-19 19:45
Oh and one other thing. When leveling up your island and claiming the reward it does not give it to you.

**Comment by sh0inx** [comment] 2024-11-20 15:56
Duplicate of #809

**Closed by sh0inx** 2024-11-20 15:56 UTC
Labels: bug, unconfirmed

**Comment by treasurebro123** [comment] 2024-11-21 00:13
Did you scope the additional comments too?

**Comment by sh0inx** [comment] 2024-11-21 00:14
yup

**Comment by sh0inx** [comment] 2024-11-21 00:15
btw i notice you're on beta 3
its not going to help you much in the way of fixing this issue, but switching to beta 4 (in our discord) will fix a couple other issues you might encounter

**Comment by treasurebro123** [comment] 2024-11-21 21:48
Oh really I haven't seen the beta 4. When I try to join the discord the link does not seem to work for me. Aside from a few bugs the plugin has been really great so far I like what you guys have created a lot!
Thanks for the feedback.

**Comment by treasurebro123** [comment] 2024-11-21 21:53
Invite link decided to work for me this time I'll check it out thanks again sh0inx
