### ISSUE TITLE
Island crystal money bug

### ISSUE THREAD

**Issue by xsorencoolx** [Iridium-Development/IridiumSkyblock#335] opened 2021-08-01 10:55 UTC
Hello I've got into bug that my players' island money or crystal getting disappear, but there is weird thing that it won't remove after server restart it will get back after minute or hour not sure how much time it will disappear again my guess about this is its SQL bug that plugin cant read it again, and it will get reset after restart plugin read SQL and all stuff will be back again

**Comment by PeachesMLG** [comment] 2021-08-01 11:00
Duplicate of https://github.com/Iridium-Development/IridiumSkyblock/issues/323

**Closed by PeachesMLG** 2021-08-01 11:00 UTC
Labels: bug
