### ISSUE TITLE
Mushroom Island won't generate (again)

### ISSUE THREAD

**Issue by Strahilchu** [Iridium-Development/IridiumSkyblock#576] opened 2022-01-22 15:59 UTC
**Describe the bug**
It's like this bug keeps returning at random times!! It's been fixed before and now again.

[15:54:57 ERROR]: Could not pass event AsyncPlayerChatEvent to IridiumSkyblock v3.2.3
java.lang.NoSuchMethodError: 'dev.rosewood.rosestacker.nms.object.StackedSpawnerTile dev.rosewood.rosestacker.stack.StackedSpawner.getSpawnerTile()'
        at com.iridium.iridiumskyblock.support.RoseStackerSupport.getExtraSpawners(RoseStackerSupport.java:28) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.getIslandSpawnerAmount(IslandManager.java:863) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.database.Island.lambda$getValue$1(Island.java:235) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.Cache.getCache(Cache.java:16) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.database.Island.getValue(Island.java:227) ~[IridiumSkyblock-3.2.3.jar:?]
        at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473) ~[?:?]
        at java.util.Collections$ReverseComparator2.compare(Collections.java:5397) ~[?:?]
        at java.util.TimSort.binarySort(TimSort.java:296) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:239) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1307) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.lambda$getIslands$45(IslandManager.java:1011) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.Cache.getCache(Cache.java:16) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.getIslands(IslandManager.java:1010) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.placeholders.Placeholders.getIslandTopPlaceholders(Placeholders.java:179) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.placeholders.Placeholders.<clinit>(Placeholders.java:33) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.iridium.iridiumskyblock.listeners.PlayerChatListener.onPlayerChat(PlayerChatListener.java:52) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor366.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-38]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[pufferfish-1.18.1.jar:git-Pufferfish-38]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[pufferfish-1.18.1.jar:git-Pufferfish-38]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[pufferfish-1.18.1.jar:git-Pufferfish-38]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2205) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2116) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2082) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by dlsf** [comment] 2022-01-22 17:36
Fixed by #556, duplicate of #557

**Comment by dlsf** [comment] 2022-01-22 17:36
Wait for the next update, download the beta version from GitHub Actions, or ask for it on our Discord server.

**Closed by dlsf** 2022-01-22 17:36 UTC
Labels: bug, duplicate
