### ISSUE TITLE
Rewards infinitely clickable in /is rewards

### ISSUE THREAD

**Issue by Overzing** [Iridium-Development/IridiumSkyblock#859] opened 2024-05-23 12:00 UTC
**Describe the bug**
Any mission sometimes gives infinitely clickable rewards. To fix that infinitely clickable reward to the user, sometimes just /is reload or /restart is enough
[rs9sY8W.txt](https://github.com/Iridium-Development/IridiumSkyblock/files/15416450/rs9sY8W.txt) --> Latest Logs

**To Reproduce**

**Expected behavior**

**Server and Plugin Version**
This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Plugin IridiumSkyBlock: 4.0.9.1

**Screenshots**

**Logs**
https://api.mclo.gs/1/raw/rs9sY8W --> Latest Logs
**Additional context**

**Comment by Grellim** [comment] 2024-05-29 22:38
I'm getting the same

**Comment by theRealhoi12** [comment] 2024-09-02 18:10
Managed to recreate the infinite clickable reward by finishing a mission, deleting/adding a completely NEW mission topic in the missions.yml, then /is reload. 

See video below for the steps performed.
https://youtu.be/tb9zx8EYk-M
https://youtu.be/9rCbIbPzpGc

**Comment by sh0inx** [comment] 2024-11-20 15:55
Duplicate of #809

**Closed by sh0inx** 2024-11-20 15:55 UTC
Labels: bug, unconfirmed
