### ISSUE TITLE
Trusted bypass limits

### ISSUE THREAD

**Issue by Baxer97** [Iridium-Development/IridiumSkyblock#580] opened 2022-01-23 00:08 UTC
**Describe the bug**
Ttrusted player (not invited) can bypass the spawner and hopper limit. Let's say that the spawner limit is 4 and there are already 4 spawner placed on the island: in this case the trusted player can't place anymore spawners but if a member of the island breaks one of the spawners the trusted player is not affected anymore by the limit and can place as many spawners as he wants. Same for hoppers. Thanks for taking the time to read this

**Steps to reproduce the behavior:**
1. Trust your friend
2. Let him place limited blocks

**Server and Plugin Version**
AirPlane 1.17.1 / IridiumSkyBlock 3.2.3

**Video**
https://www.youtube.com/watch?v=oVbQL4oT25A

**Logs**
No error in console

**Comment by dlsf** [comment] 2022-01-23 10:54
Duplicate of #564. Please don't create new copies of your issues, we are aware of them.

**Closed by dlsf** 2022-01-23 10:54 UTC
Labels: bug, duplicate
