### ISSUE TITLE
IridiumSkyblock Menu Item Head Flickering Issue

### ISSUE THREAD

**Issue by RealisticCarrot** [Iridium-Development/IridiumSkyblock#744] opened 2023-09-30 00:10 UTC
Hello, some of the item heads in parts of the Iridiumskyblock menu are flickering between the default head and the head I set. 

Server Version: paper-1.20.1-195.jar
Plugin Version: 4.0.6

![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/69768653/f964e92e-fc7b-4ae7-b08c-2a48584dcf81)
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/69768653/a831bf68-e9aa-413f-ac38-dba30f8c8e81)

https://github.com/Iridium-Development/IridiumSkyblock/assets/69768653/059ab41d-0079-47d0-9500-e964fa837e1d

**Comment by sh0inx** [comment] 2023-09-30 00:16
that is really weird, have you tried lowering your refresh interval at all? im going to see if i can replicate this

**Comment by RealisticThreat** [comment] 2023-09-30 00:17
Yeah, cause not all of the menu item heads are flickering.

**Comment by sh0inx** [comment] 2023-09-30 00:19
which menus have this occurrence? we can probably narrow down the cause with that information

**Comment by RealisticThreat** [comment] 2023-09-30 00:37
The main menu /is menu, the island members menu, and the island bank menu.

**Comment by Faun471** [comment] 2023-10-02 20:17
your full log file would greatly help

**Comment by RealisticCarrot** [comment] 2023-10-03 08:08
https://pastebin.com/rEXyDXLw

**Comment by PeachesMLG** [comment] 2023-10-21 11:10
Im wondering if this is a spigot bug since I was only able to replicate it once I updated

**Comment by sh0inx** [comment] 2023-10-21 11:27
same thing here, I can't pinpoint a cause tho

**Comment by lvanko** [comment] 2023-10-27 08:08
Having the same issue.

**Comment by nickynice1** [comment] 2023-12-17 21:28
same issue here.

**Comment by LucaMezz** [comment] 2023-12-21 23:40
same issue

**Comment by PeachesMLG** [comment] 2024-01-15 15:45
Seems to have been introduced in this Paper commit when updating to 1.20.2 https://github.com/PaperMC/paper/commit/e284bb12156fad92767ceadf3d5e57cbc71e5b21

**Comment by sh0inx** [comment] 2024-01-15 15:47
if thats the case that means spigot wont replicate it, im going to try that rq

**Comment by PeachesMLG** [comment] 2024-01-15 15:54
Spigot also has the same issues between 1.20.1 and 1.20.2, not sure if its a specific commit that caused it though since I cba to compile it

**Comment by sh0inx** [comment] 2024-01-15 15:55
i do it dw

**Comment by PeachesMLG** [comment] 2024-01-15 16:49
Fixed in https://github.com/Iridium-Development/IridiumCore/blob/master/plugin/src/main/java/com/iridium/iridiumcore/utils/ItemStackUtils.java#L141C46-L141C46

**Closed by PeachesMLG** 2024-01-15 16:49 UTC
Labels: bug, confirmed
