### ISSUE TITLE
Leaves decay on island create

### ISSUE THREAD

**Issue by srnyx** [Iridium-Development/IridiumSkyblock#407] opened 2021-09-19 02:27 UTC
**Describe the bug**
Islands decay right when a player creates an island

**Expected behavior**
The initial leaves created when the island is first created shouldn't decay

**Server Version and Plugin Version**
This server is running Purpur version git-Purpur-1393 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3ff85ed on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1346 (MC: 1.17.1)

v3.1.1

**Additional context**
I don't want leaves to just not decay, so disabling leaf decay using WorldGuard won't work.
I've also tried editing the schematics but it still happens.

**Comment by MertUnverdi** [comment] 2021-09-19 02:33
its about our schematic thing will be fixed soon 
duplicate of #340

**Comment by dlsf** [comment] 2021-09-19 13:44
I actually don't think that's related

**Comment by srnyx** [comment] 2021-09-19 13:53
> I actually don't think that's related

It isn't?

**Comment by Faun471** [comment] 2021-09-19 14:44
> > I actually don't think that's related
> 
> It isn't?

It's not related to the schematic issue, but still an issue nonetheless. Could you try using F3 to check if the leaves are "persistent"?

**Comment by srnyx** [comment] 2021-09-19 14:48
> Could you try using F3 to check if the leaves are "persistent"?

They aren't, but I specifically made the leaves persistent using WorldEdit for the schematics (`//replacenear 50 jungle_leaves jungle_leaves[persistant=true]`) and they didn't decay then.

**Comment by PeachesMLG** [comment] 2021-10-03 16:21
In island settings we have a setting which can disable leaf decay

**Comment by srnyx** [comment] 2021-10-03 17:07
> In island settings we have a setting which can disable leaf decay

Doesn't prevent the leaves that are there upon island creation though

**Closed** 2021-10-03 17:29 UTC
Labels: bug, good first issue, confirmed
