### ISSUE TITLE
Console error when creating island for the first time (1.12.2) - no in-game bugs

### ISSUE THREAD

**Issue by TheJoshue** [Iridium-Development/IridiumSkyblock#190] opened 2021-06-19 12:47 UTC
Using paper-1.12.2 (1618) server version.
Running on Windows 10 & Ubuntu18.04, running Java 8
I get this error when executing `/is` for the first time, and AFTER i select an island type to generate personal new island, this error happens only in console - doesn't affect anything in-game from what i have seen.
* Running BETA release that I got from one of STAFF role-d members = v3.0.4 (but beta)

```[13:49:07 INFO]: TheJoshua issued server command: /is
[13:49:07 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_12_R1! Trying to find NMS support
[13:49:07 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_12_R1' loaded!
[13:49:07 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[13:49:07 INFO]: [NBTAPI] [NBTAPI] The NBT-API seems to be up-to-date!
[13:49:12 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[Paper-1.12.2.jar:git-Paper-1618]
        at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.io.ObjectInputStream.checkResolve(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:143) ~[?:?]
        at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_291]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[13:49:12 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[Paper-1.12.2.jar:git-Paper-1618]
        at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.io.ObjectInputStream.checkResolve(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:143) ~[?:?]
        at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_291]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[13:49:12 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[Paper-1.12.2.jar:git-Paper-1618]
        at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.io.ObjectInputStream.checkResolve(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:143) ~[?:?]
        at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_291]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[13:49:12 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[Paper-1.12.2.jar:git-Paper-1618]
        at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.io.ObjectInputStream.checkResolve(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject0(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at java.io.ObjectInputStream.readObject(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:143) ~[?:?]
        at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_291]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_291]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_291]
        at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
        at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
```

**Comment by PeachesMLG** [comment] 2021-06-21 20:41
Duplicate of https://github.com/Iridium-Development/IridiumSkyblock/issues/142

**Closed by PeachesMLG** 2021-06-21 20:41 UTC
Labels: bug, not confirmed
