### ISSUE TITLE
Own Island Schematics Not Working

### ISSUE THREAD

**Issue by ImTitan** [Iridium-Development/IridiumSkyblock#398] opened 2021-09-09 21:22 UTC
So I'm a server owner that is trying to config different areas of this plugin, including changing the schematics for the island, but when I create my own and put it into the server, stop/start it, do /is reload, almost anything I could think of, it won't work. I've changed the schematics.yml so when I create a new world and select any one, it will create my schematic, but for some reason it creates a nether island instead. I've also tried changing the schematic name from island.iridiumschem to island.schem and it still wouldn't do anything.

When I put in a different schematic (built in the plugin), it seems there is no problem, just when I put mine in, there is.

My Iridium Skyblock version is 3.1.1 (Latest from this post)

And from what I can see, there are no console errors.

Thanks.  :)

**Comment by dlsf** [comment] 2021-09-09 21:49
How did you create the schematic? Can you send us your schematics.yml?

**Comment by ImTitan** [comment] 2021-09-09 22:14
I created it on a single player world with World Edit mod downloaded. Using //pos1, //pos2, //expand vert, and //copy. Then I would do //schem save [name].

`---
schematics:
  desert:
    item:
      material: "PLAYER_HEAD"
      amount: 1
      displayName: "&aStarter Island"
      headData: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQ5YzYzYmM1MDg3MjMzMjhhMTllNTk3ZjQwODYyZDI3YWQ1YzFkNTQ1NjYzYWMyNDQ2NjU4MmY1NjhkOSJ9fX0="
      headOwner: null
      lore:
      - "&7Click to create your island!"
      slot: 11
    xHome: 0.0
    yHome: 100.0
    zHome: 0.0
    yawHome: 90.0
    overworld:
      biome: "PLAINS"
      schematicID: "starter_overworld.iridiumschem"
    nether:
      biome: "NETHER_WASTES"
      schematicID: "starter_overworld.iridiumschem"
    end:
      biome: "THE_END"
      schematicID: "starter_overworld.iridiumschem"
  jungle:
    item:
      material: "PLAYER_HEAD"
      amount: 1
      displayName: "&b&lJungle Island"
      headData: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgzYWRmNDU2MGRlNDc0MTQwNDA5M2FjNjFjMzNmYjU1NmIzZDllZTUxNDBmNjIwMzYyNTg5ZmRkZWRlZmEyZCJ9fX0="
      headOwner: null
      lore:
      - "&7A starter jungle island."
      slot: 13
    xHome: 1.5
    yHome: 95.0
    zHome: 0.5
    yawHome: 90.0
    overworld:
      biome: "JUNGLE"
      schematicID: "starter_overworld.iridiumschem"
    nether:
      biome: "NETHER_WASTES"
      schematicID: "starter_overworld.iridiumschem"
    end:
      biome: "THE_END"
      schematicID: "starter_overworld.iridiumschem"
  mushroom:
    item:
      material: "PLAYER_HEAD"
      amount: 1
      displayName: "&b&lMushroom Island"
      headData: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzZkMWZhYmRmM2UzNDI2NzFiZDlmOTVmNjg3ZmUyNjNmNDM5ZGRjMmYxYzllYThmZjE1YjEzZjFlN2U0OGI5In19fQ="
      headOwner: null
      lore:
      - "&7A starter mushroom island."
      slot: 15
    xHome: -1.5
    yHome: 95.0
    zHome: -0.5
    yawHome: 90.0
    overworld:
      biome: "MUSHROOM_FIELDS"
      schematicID: "starter_overworld.iridiumschem"
    nether:
      biome: "NETHER_WASTES"
      schematicID: "starter_overworld.iridiumschem"
    end:
      biome: "THE_END"
      schematicID: "starter_overworld.iridiumschem"
`

**Comment by MertUnverdi** [comment] 2021-09-09 22:18
we have custom model schematic thing u just changed the file ext, it wont work
Save schematics with /is pos 1|2 then /is saveschematic

**Comment by MertUnverdi** [comment] 2021-09-09 22:19
The issue is this, if wont fixed you can reopen it, thanks 👍🏻

**Closed by MertUnverdi** 2021-09-09 22:19 UTC
Labels: bug, not confirmed
