### ISSUE TITLE
SQL error missions

### ISSUE THREAD

**Issue by nickynice1** [Iridium-Development/IridiumSkyblock#780] opened 2023-12-26 21:36 UTC
After completing a mission I get an SQL error in console.

Log:
https://mclo.gs/8YMhMT4

Running on Paper 1.20.1 latest plugin version 4.0.8

**Comment by sh0inx** [comment] 2023-12-27 23:51
duplicate of [725](https://github.com/Iridium-Development/IridiumSkyblock/issues/725)

**Closed** 2023-12-27 23:51 UTC
Labels: bug, unconfirmed
