### ISSUE TITLE
Missions not resetting

### ISSUE THREAD

**Issue by Jbacot** [Iridium-Development/IridiumSkyblock#655] opened 2022-05-08 02:56 UTC
**Describe the bug**
Daily missions are not resetting after the missions pass. The GUI resets but the data does not.
I started a daily mission and didn't finish it. Once the day passed and the mission gui cycles, I am able to complete other missions but the past daily missions can still be completed. 
For example, I had a `MINE` redstone mission that I completed half way through. The next day (after the mission gui cycled) I was testing something and I finished the redstone mission even though it was not in the mission gui. 
Today, I checked the GUI and without even mining pumpkins, yet I had already had some counted towards the quest.

**To Reproduce**
1. Start a mission and start some of it
2. The next day, after the gui has cycled, finish the quest
3. You will be rewarded with completing it

**Expected behavior**
Missions reset daily and do not continue on to count after the day has completed.

**Server and Plugin Version**
Paper version git-Paper-312 (MC 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ce059b4)
IridiumSkyblock version 3.2.8

**Comment by dlsf** [comment] 2022-05-13 16:41
Duplicate of #605. Please add further information to that issue if you believe something is missing.

**Closed by dlsf** 2022-05-13 16:41 UTC
Labels: bug, unconfirmed
