### ISSUE TITLE
CONSOLE database error

### ISSUE THREAD

**Issue by ChibeMeliodas** [Iridium-Development/IridiumSkyblock#776] opened 2023-12-18 19:40 UTC
[16:30:46 WARN]: java.sql.SQLException: Unable to run insert stmt on object com.iridium.iridiumteams.database.TeamMissionData@284d5891: INSERT INTO `team_mission_data` (`mission_id` ,`mission_index` ,`progress` ) VALUES (?,?,?)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:396)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:38)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:212)
[16:30:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[16:30:46 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:30:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:30:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:30:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:30:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:30:46 WARN]: Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: team_mission_data.mission_id, team_mission_data.mission_index)
[16:30:46 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[16:30:46 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[16:30:46 WARN]:        at org.sqlite.core.DB.execute(DB.java:985)
[16:30:46 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:1054)
[16:30:46 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:122)
[16:30:46 WARN]:        at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454)
[16:30:46 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:121)
[16:30:46 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:185)
[16:30:46 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[16:30:46 WARN]:        ... 11 more

![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/33189940/b3de5897-b6f9-42e9-aa93-c1663248ebde)

**Comment by sh0inx** [comment] 2023-12-18 19:45
duplicate of [725](https://github.com/Iridium-Development/IridiumSkyblock/issues/725)

**Closed** 2023-12-18 19:45 UTC
Labels: bug, unconfirmed

**Comment by ChibeMeliodas** [comment] 2023-12-18 20:07
> duplicate of [725](https://github.com/Iridium-Development/IridiumSkyblock/issues/725)

no it's not, because the version of plugin is 4.0.8 and the server is paper 1.20.2
