### ISSUE TITLE
island crystal disappears randomly

### ISSUE THREAD

**Issue by tksky1** [Iridium-Development/IridiumSkyblock#325] opened 2021-07-29 06:06 UTC
**Describe the bug**
I'm not a native speaker so sorry for my English.
It's a nice plugin but there's something disturbing.
Some of the player reported that their crystals were set to 0 for no reason, both displayed in island bank and placeholder.
After a while the amount of crystal comes to normal again.
While the crystals were missing, players can't buy anything.

This problem happened before, and now it's happening again and affecting more players.
It is not a huge problem but it does scare players a lot. 
I don't know if it's a configuration problem, but pls fix it as soon as possible.

**To Reproduce**
unknow

** Server Version and Plugin Version**
Paper version git-Paper-130 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2f1f1b7)
plugin version 3.0.7

**Logs**
there are "Null pointer exception" but I don't know whether it's something related.

 [IridiumSkyblock] Plugin IridiumSkyblock v3.0.7 generated an exception while executing task 5920785
java.lang.NullPointerException: null
[11:13:25 WARN]: [IridiumSkyblock] Task #1739 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: null

**Comment by dlsf** [comment] 2021-07-29 10:19
This error should have been fixed in IridiumSkyblock 3.0.7. 

Regarding that error messages: It is shortened, we can't work with it. Can you find the full one anywhere?

**Comment by Sixsoul** [comment] 2021-07-29 13:17
It's not fixed in 3.0.7! Have the same issue!

**Comment by tksky1** [comment] 2021-07-29 16:21
[00:18:06 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.7 generated an exception while executing task 10924
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.gui.GUI.lambda$getInventory$0(GUI.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-130]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-130]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:07 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:08 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:09 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]

[00:18:10 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:11 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:12 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:12 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.7 generated an exception while executing task 11277
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.gui.GUI.lambda$getInventory$0(GUI.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-130]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-130]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:13 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.7 generated an exception while executing task 11286
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.gui.GUI.lambda$getInventory$0(GUI.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-130]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-130]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:13 WARN]: [IridiumSkyblock] Task #1836 for IridiumSkyblock v3.0.7 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:18:13 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.7 generated an exception while executing task 11306
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "lines" is null
        at com.iridium.iridiumcore.utils.StringUtils.processMultiplePlaceholders(StringUtils.java:48) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:57) ~[?:?]
        at com.iridium.iridiumskyblock.gui.BankGUI.addContent(BankGUI.java:39) ~[?:?]
        at com.iridium.iridiumskyblock.gui.GUI.lambda$getInventory$0(GUI.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-130]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-130]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by tksky1** [comment] 2021-07-29 16:33
This error from the log may due to my configuration to hide a button in bank GUI. So it may have nothing to do with the bug.
Maybe a database problem?

**Comment by dlsf** [comment] 2021-07-29 18:09
Yeah, that error has indeed nothing to do with this issue.

@PeachesMLG maybe there are still old, duplicate database entries? That could be the reason why these issues still show up

**Comment by tksky1** [comment] 2021-07-30 10:45
Some of my players said their island levels and upgrades are reset as well, and many of them havn't got their data restored.
I'm worrying that they may lose their data and that will be a real problem.

**Comment by Sixsoul** [comment] 2021-07-30 13:18
> 
> 
> Some of my players said their island levels and upgrades are reset as well, and many of them havn't got their data restored.
> I'm worrying that they may lose their data and that will be a real problem.

Yep, same here. Island upgrades reset, levels reset, bank resets. Plugin is unusable right now honestly.

**Comment by PeachesMLG** [comment] 2021-07-31 21:02
Duplicate of #323

**Closed by PeachesMLG** 2021-07-31 21:02 UTC
Labels: bug, not confirmed
