### ISSUE TITLE
World border does not fit to island size

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#302] opened 2021-07-21 10:27 UTC
**Describe the bug**
World border does not fit to island size if we have even sizes

**To Reproduce**
1. Make sure the size of the island is even.
2. Try to build platform in each direction
3. And see that 2 side of the border are further from the border of the island

**Expected behavior**
Fit border to island size

** Server Version and Plugin Version**
Server version: 1.16.5
Plugin version: 3.0.6

**Screenshots**
![bug](https://user-images.githubusercontent.com/8580908/126474014-8ed66b20-032f-4832-9214-b12c2df504e6.gif)

**Additional context**
I think problem is in minecraft border architecture and offset added here
https://github.com/Iridium-Development/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java#L47

**Comment by MertUnverdi** [comment] 2021-07-21 10:31
@dlsf he was fixed this issue for 1000 times "(

**Comment by dlsf** [comment] 2021-07-21 12:29
In what version was the island created, what's the distance between islands and what's the size of the island?

**Comment by xReveres** [comment] 2021-07-21 12:57
I don't remember v3.0.3 or v3.0.4?

**Comment by xReveres** [comment] 2021-07-22 09:24
Looks similar #265

**Comment by dlsf** [comment] 2021-07-23 18:39
Duplicate of #265 then, although I have to thank you for your extra information

**Closed by dlsf** 2021-07-23 18:39 UTC
Labels: bug
