### ISSUE TITLE
IridiumSchematic does not support new blocks and biomes are not being set

### ISSUE THREAD

**Issue by Nubebuster** [Iridium-Development/IridiumSkyblock#156] opened 2021-06-15 06:40 UTC
When I save a schematic in the nether with soul soil blocks for example and then load a new island with that schematic, those new blocks are not placed.

Also the biomes are not being set in general.

**Comment by Nubebuster** [comment] 2021-06-15 07:14
Also portal blocks are not pasted

**Comment by dlsf** [comment] 2021-06-15 08:46
Duplicate of #75

**Closed by dlsf** 2021-06-15 08:46 UTC
Labels: bug, invalid
