### ISSUE TITLE
1.12.2 still more bug

### ISSUE THREAD

**Issue by p82183645** [Iridium-Development/IridiumSkyblock#223] opened 2021-06-28 23:19 UTC
if check this item, the player client will stop responding
Please fix these issues. There are several versions.
![image](https://user-images.githubusercontent.com/5382252/123715059-1d25f980-d8aa-11eb-971b-69d73167726d.png)

![image](https://user-images.githubusercontent.com/5382252/123715071-257e3480-d8aa-11eb-8985-cfd9bbad6768.png)
![image](https://user-images.githubusercontent.com/5382252/123715214-6118fe80-d8aa-11eb-8a86-db7545a38b6f.png)

**if create skyblock happen**

`[07:12:05] [Server thread/INFO]: AriaMura issued server command: /is
[07:12:11] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[patched_1.12.2.jar:git-Paper-1618]
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1718) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_292]
	at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:133) ~[?:?]
	at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_292]
	at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[07:12:11] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[patched_1.12.2.jar:git-Paper-1618]
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1718) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_292]
	at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:133) ~[?:?]
	at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_292]
	at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[07:12:11] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[patched_1.12.2.jar:git-Paper-1618]
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1718) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_292]
	at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:133) ~[?:?]
	at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_292]
	at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[07:12:11] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: null
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:540) ~[patched_1.12.2.jar:git-Paper-1618]
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1718) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503) ~[?:1.8.0_292]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461) ~[?:1.8.0_292]
	at com.iridium.iridiumcore.utils.ItemStackUtils.deserialize(ItemStackUtils.java:133) ~[?:?]
	at com.iridium.iridiumskyblock.BlockData.lambda$setBlock$1(BlockData.java:60) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505) ~[?:1.8.0_292]
	at com.iridium.iridiumskyblock.BlockData.setBlock(BlockData.java:60) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.pasteSchematic(SchematicManager.java:108) ~[?:?]
	at com.iridium.iridiumskyblock.managers.SchematicManager.lambda$pasteSchematic$0(SchematicManager.java:116) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]`
	
![image](https://user-images.githubusercontent.com/5382252/123715790-a25dde00-d8ab-11eb-8d7a-ab293c9cd085.png)

**Comment by dlsf** [comment] 2021-06-29 11:11
Duplicate of #142

**Closed** 2021-06-29 11:11 UTC
Labels: bug, duplicate
