### ISSUE TITLE
Islands have more then one biome

### ISSUE THREAD

**Issue by tjaws** [Iridium-Development/IridiumSkyblock#201] opened 2021-06-22 04:50 UTC
When creating an island it should for example have biome: "PLAINS" but it has a lot of different biomes.
The bigger your island gets the more biomes. It also will not rain in some chunks for this reason.

**Comment by Nubebuster** [comment] 2021-06-22 13:56
Duplicate of #75

**Comment by PeachesMLG** [comment] 2021-06-22 14:25
> Duplicate of #75

No its not? Its bgecause we never actually change the biome, I belive ori is making a pr for this

**Comment by dlsf** [comment] 2021-06-22 16:28
Duplicate of #188

**Closed by dlsf** 2021-06-22 16:28 UTC
