### ISSUE TITLE
Schematica loading issue

### ISSUE THREAD

**Issue by SamGamerYT** [Iridium-Development/IridiumSkyblock#204] opened 2021-06-22 16:56 UTC
`/is pos1, /is pos2, /is saveschematic <name>`

Did the following to make it work but currently I'm currently having issues with the plugin registering some blocks positions and portal block of Nether Portal

**ERRORS**
```
[03:26:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=104, z=-172}
[03:26:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=104, z=-171}
[03:26:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=104, z=-170}
[03:26:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=105, z=-172}
[03:26:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=105, z=-171}
[03:26:50 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=105, z=-170}
[03:26:51 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=106, z=-172}
[03:26:51 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=106, z=-171}
[03:26:51 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=106, z=-170}
[03:26:51 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=107, z=-172}
[03:26:51 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=107, z=-171}
[03:26:51 ERROR]: POI data mismatch: never registered at BlockPosition{x=7, y=107, z=-170}
```

This is how it suppose to look like
https://cdn.discordapp.com/attachments/592092308514537510/856843271673348096/2021-06-22_03.23.29.png

This is the end result
https://cdn.discordapp.com/attachments/592092308514537510/856843294084038686/2021-06-22_03.23.47.png

**Comment by dlsf** [comment] 2021-06-22 20:42
Duplicate of #75

**Closed by dlsf** 2021-06-22 20:42 UTC
Labels: bug, invalid
